baseURL = 'https://example.org/'
locale = 'en-US'
title = 'Welcome to my clouds theme'

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1
    [menus.main.params]
      image = '/digigarden2025.png'

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
